### ISSUE TITLE
make a good design of the authentication page

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#10]
Check sites like https://www.framer.com/, https://ui.aceternity.com/, https://www.classroomio.com/, https://www.classroomio.com/ to get design ideas

It should be modern UI

**Comment by Pratik-050** [comment]
@ItsRoy69 I can try it. Please assign it to me

**Comment by ItsRoy69** [comment]
Its been a month and this issue is still inactive, I'll have to assign someone else @Pratik-050

**Comment by JangidRkt08** [comment]
@ItsRoy69 Please assign me this issue under iwoc2.0

**Comment by Tanishka023** [comment]
@ItsRoy69 Can you please assign this to me under IWOC'24

**Comment by ItsRoy69** [comment]
@Tanishka023 its first come first serve basis.. so.. let's see if @JangidRkt08 does.. orelse I'll assign you, for now you can check other issues.. or create one

**Comment by Tanishka023** [comment]
> @Tanishka023 its first come first serve basis.. so.. let's see if @JangidRkt08 does.. orelse I'll assign you, for now you can check other issues.. or create one

Okay! That's fine.

**Comment by ItsRoy69** [comment]
> > @Tanishka023 its first come first serve basis.. so.. let's see if @JangidRkt08 does.. orelse I'll assign you, for now you can check other issues.. or create one
> 
> Okay! That's fine.

@Tanishka023 you can work on other issues.

**Comment by ItsRoy69** [comment]
@JangidRkt08 are you still working on this issue ?
