### ISSUE TITLE
Unwanted text on the home page under nav bar

### ISSUE THREAD

**Issue by godspeed-03** [WikiPortal/DoodleCollab#100]
### Description

Issue happening at : https://doodlecollab.vercel.app/

Below : Navigation bar / Header

On the home page there is an unwanted text or either component is not rendered as expected.

### Screenshots

![Screenshot 2024-01-23 183453](https://github.com/WikiPortal/DoodleCollab/assets/119731754/e63bb09d-61bc-45d4-bd4a-4a6bed782290)

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [X] I am participating in IWOC
- [X] I am willing to work on this issue (blank for no)

**Comment by godspeed-03** [comment]
Hii @ItsRoy69, assign this to me So that I can fix it or improve the homebanner section.

**Comment by ItsRoy69** [comment]
It is given to show the space kept for putting the banner component
