### ISSUE TITLE
Bug: The slider inside toggle button moves outside

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#101]
### Description

When user clicks on the toggle button for dark or light mode, the slider button moves out of the box border

### Proposed Solution

The inner toggle button shouldn't move outside the external button

### Screenshots

![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/2d9ebc45-a517-40c8-b137-f79c6e02bbc8)
---
![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/d226631f-6c9b-4e58-88c3-0eafefa3732d)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (leave this unchecked for no).

**Comment by hemanth-kumar-boddeda** [comment]
Hi @ItsRoy69, Iam ready to do this, could you please assign it to me?

**Comment by ItsRoy69** [comment]
Go for it

**Comment by hemanth-kumar-boddeda** [comment]
@ItsRoy69 kindly check the below snip, where the slider will not move outside of the bar, hope to hear from you soon.
https://github.com/WikiPortal/DoodleCollab/assets/82110100/fd49d8e0-de74-40eb-ac33-e95b636589ee

**Comment by hemanth-kumar-boddeda** [comment]
I have made changes in your existing toggle bar,
Verified by reducing the speed of 0.5x ( 00:08 in the video),
 kindly check and update back so that I can push it.

https://github.com/WikiPortal/DoodleCollab/assets/82110100/c73e48e1-4f86-4160-a746-89da70ae6ebc

**Comment by ItsRoy69** [comment]
LGTM, make a PR
