### ISSUE TITLE
Website issue: The navbar needs to be responsive 

### ISSUE THREAD

**Issue by HeisRoy33** [WikiPortal/DoodleCollab#104]
### Description

The navbar of the website is not responsive according to different screen sizes

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [ ] I am participating in IWOC
- [ ] I am willing to work on this issue (blank for no)

**Comment by YashNuhash** [comment]
I would good for me , you can assign me for it

**Comment by ItsRoy69** [comment]
Go for it

**Comment by sudeepkudari0** [comment]
I have created a PR for making navbar fixed, if it gets accepted i would suggest the persion working on this issue get branch updated

**Comment by hemanth-kumar-boddeda** [comment]
@ItsRoy69  Kindly got through the assisted snip as I have made the navbar repsonsive as needed.
https://github.com/WikiPortal/DoodleCollab/assets/82110100/f56aec00-4e59-443b-9753-05b0123a04a2

**Comment by ItsRoy69** [comment]
@hemanth-kumar-boddeda kindly work on issues where i have assigned and don't go on commenting on several issues, as it gets spammed and would be marked as spam next time

**Comment by HemantSingh2070** [comment]
Hello Sir , I am ### **Hemant Singh (HemantSingh2070)** participating in **_IWOC_** I have done some changes . Made the **navigation bar** responsive  .Please accept my pr.
![pr](https://github.com/WikiPortal/DoodleCollab/assets/148877989/cf9b4cee-02ad-47da-b534-aa2294f32031)

**Comment by ItsRoy69** [comment]
Can you make a PR?
