### ISSUE TITLE
Website issue: Make the "join us" section responsive

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#105]
### Description

The JOIN US section breaks as user opens via mobile phone or any other screen sizes which is not supposed to happen , I have attached the styling after responsiveness is applied to screens

### Screenshots

![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/3b8e88f0-04e0-4b0b-869c-4488064e631f)
![Screenshot 2024-01-24 084444](https://github.com/WikiPortal/DoodleCollab/assets/78967360/7d554de7-1800-4962-8085-274c91716d4d)
![Screenshot 2024-01-24 084522](https://github.com/WikiPortal/DoodleCollab/assets/78967360/8cdbcbfd-6e8b-40e2-bd15-8c0053e4840a)
![Screenshot 2024-01-24 084535](https://github.com/WikiPortal/DoodleCollab/assets/78967360/30113b91-7748-435c-8de5-eb31f51d2f91)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [ ] I am participating in IWOC
- [ ] I am willing to work on this issue (blank for no)

**Comment by mehedihasan2810** [comment]
Hi @ItsRoy69 I would like to make a PR for this issue. Please assign it to me.

**Comment by ItsRoy69** [comment]
Go for it

**Comment by hemanth-kumar-boddeda** [comment]
Hi we can make it responsive it less than a day, could you please assign it to me?

**Comment by hemanth-kumar-boddeda** [comment]
Hi @mehedihasan2810,
 you completed it successfully?
