### ISSUE TITLE
Bug: Fix the sketchbook error after loggin in

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#112]
### Description

When user logs in, he/she faces an issue even after using verified credentials that the user needs to Login first.
Below shown the issue.

### Proposed Solution

The webapp should successfully redirect to sketchbook page after logging in and if user tries to access the sketchbook without logging in then it will show "Login first".

### Screenshots

[Issue.webm](https://github.com/WikiPortal/DoodleCollab/assets/78967360/0cfe86d1-45a9-4199-9495-26791a31627e)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (leave this unchecked for no).

**Comment by ItsRoy69** [comment]
Go for it

**Comment by Bikram-ghuku** [comment]
Can I work on this issue? Please assign this to me

**Comment by praptisharma28** [comment]
assign me @ItsRoy69 under iwoc

**Comment by ItsRoy69** [comment]
@praptisharma28 since @Bikram-ghuku asked first so
