### ISSUE TITLE
Website issue: Add a home button and functionality

### ISSUE THREAD

**Issue by praptisharma28** [WikiPortal/DoodleCollab#117]
### Description

The home page opens when we click on logo and there is not button there, need to add a button in navbar and the functionality too, otherwise it is odd.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [X] I am participating in IWOC
- [X] I am willing to work on this issue (blank for no)

**Comment by ItsRoy69** [comment]
Don't  understand what you're trying to implement . Can you explain a bit more ?

**Comment by praptisharma28** [comment]
don't worry, I will implement this in this issue only https://github.com/WikiPortal/DoodleCollab/issues/118#issuecomment-1911514621

**Comment by godspeed-03** [comment]
I think it's not necessary to add button as the navbar section is good enough and could you please explain the term #odd which you have written earlier @praptisharma28.

**Comment by praptisharma28** [comment]
@godspeed-03 Like there in home in navbar, its not about it being good, its about it being fully functional. To get on the home page, we need to click ka logo (doodlecollab) which is not suitable, thats all thanks.

**Comment by ItsRoy69** [comment]
Got it, i guess it'll be better if the home page is shown conditionally according to pages, like if someone moved to features pagw, the home page text will pop up and features will appear and so on
