### ISSUE TITLE
📂Other: Add hover effects to buttons and navbar links.

### ISSUE THREAD

**Issue by praptisharma28** [WikiPortal/DoodleCollab#118]
### What would you like to share?

There is no hover on button like on discord button on homeoage and no effects on navbar links. Add creative effects there.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [X] I am participating in IWOC
- [X] I am willing to work on this issue (blank for no)

**Comment by praptisharma28** [comment]
Assign me @ItsRoy69 under iwoc

**Comment by ItsRoy69** [comment]
Go for it

**Comment by jaymehta002** [comment]
Assign me this issue
