### ISSUE TITLE
Bug: Greetings workflow is failing, need to correct it. 

### ISSUE THREAD

**Issue by praptisharma28** [WikiPortal/DoodleCollab#119]
### Description

The greetings.yml template is incorrect. 

### Proposed Solution

 Needs updation.

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (leave this unchecked for no).

**Comment by ItsRoy69** [comment]
I noticed this issue,try to fix it

**Comment by praptisharma28** [comment]
Add the tags too @ItsRoy69
