### ISSUE TITLE
🎨style: introduce hover effects to cards on home page

### ISSUE THREAD

**Issue by harmeetsingh11** [WikiPortal/DoodleCollab#120]
### What would you like to share?

**Description:**
The cards on the home page currently lack dynamic hover effects, resulting in a static appearance. To improve user experience and visual aesthetics, we should implement a hover effect along with colored borders for the cards. This enhancement should be consistent across both dark and light modes to maintain a cohesive design.

**Proposed Changes:**
- Add a subtle hover effect to the home page cards to provide visual feedback.
- Implement colored borders for the cards during the hover state for a more dynamic appearance.
- Ensure that the hover effects and colored borders are consistent and visually appealing in both dark and light modes.

**Additional Considerations:**
- Test the hover effects and colored borders across different devices and browsers to ensure compatibility.
- Consider user accessibility and ensure that the hover effects do not interfere with the overall usability of the site.

**Expected Behavior:**
- Users should experience a smooth and visually pleasing hover effect on the home page cards.
- Colored borders should enhance the visibility of the cards and provide a clear indication of the hover state.

**Screenshots**

![DoodleCollab](https://github.com/WikiPortal/DoodleCollab/assets/130365071/4fb22323-cceb-45f7-9a5b-a9beaa12bb91)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [X] I am participating in IWOC
- [X] I am willing to work on this issue (blank for no)

**Comment by jaymehta002** [comment]
Assign me this issue

**Comment by ItsRoy69** [comment]
Go for it @harmeetsingh11
