### ISSUE TITLE
📂Other: Add a link in sign up page so that if user already signed up they can navigate to log in page to log in. Do the same in log in page.

### ISSUE THREAD

**Issue by mehedihasan2810** [WikiPortal/DoodleCollab#126]
### What would you like to share?

Add a link in sign up page so that if user already signed up they can navigate to log in page to log in. Do the same in log in page.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [ ] I am participating in IWOC
- [ ] I am willing to work on this issue (blank for no)

**Comment by mehedihasan2810** [comment]
Hey @ItsRoy69 assign me for this issue

**Comment by ItsRoy69** [comment]
@mehedihasan2810 bit confused as if user is already signedup they can go from signuped page only

**Comment by mehedihasan2810** [comment]
Hey @ItsRoy69  sorry for the confusion. I meant links like the below image

![screencapture-talktide-vercel-app-auth-2024-01-26-19_39_32](https://github.com/WikiPortal/DoodleCollab/assets/117534561/e96d4da9-f8a2-4cfd-9cbc-841f70bc4cf9)

**Comment by ItsRoy69** [comment]
In the refactored design registration page, its already shown
