### ISSUE TITLE
Bug: Features tab must be responsive and below the navbar.

### ISSUE THREAD

**Issue by achyutagupta** [WikiPortal/DoodleCollab#130]
### Description

Navbar is over the features container hiding some portion of the features tab.
Features tab is not responsive.

### Proposed Solution

Add responsiveness to the features tab.

### Screenshots

![image](https://github.com/WikiPortal/DoodleCollab/assets/107514366/c31fec26-eb5e-4e34-b38b-46fee81c3caf)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (leave this unchecked for no).

**Comment by ItsRoy69** [comment]
@achyutagupta go for it
