### ISSUE TITLE
Bug: Not responsive

### ISSUE THREAD

**Issue by toffee-k21** [WikiPortal/DoodleCollab#136]
### Description

Home Page is not responsive

### Proposed Solution

due to 'navbar ' and 'trusted by developer' section.

### Screenshots

![Screenshot 2024-01-28 002945](https://github.com/WikiPortal/DoodleCollab/assets/145540627/0fa8f16e-ebed-48e2-902b-a2a327879908)

### Browser 🥦

Microsoft Edge

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (leave this unchecked for no).

**Comment by ItsRoy69** [comment]
@toffee-k21 go for it
