### ISSUE TITLE
Bug: Fix login frontend issues

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#138]
### Description

When user moves to login page, the UI is bit broken , I want the right side of the login page to be a better Ui

### Proposed Solution

UI should be a bit cleaner as I have shown below

### Screenshots

![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/27544ac2-bad0-4ae1-9abc-c2c220c892c5)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (leave this unchecked for no).

**Comment by AryanKuAg** [comment]
- [ ]  Yes I'm willing to work on this issue

**Comment by AryanKuAg** [comment]
https://github.com/WikiPortal/DoodleCollab/pull/140
Hey @ItsRoy69 , I'm a new contributor to these open source projects, I made this contribution and raised this PR, Pls let me know if there's any issue with this and pls merge this PR if its look fine to u🙂.

**Comment by ItsRoy69** [comment]
@AryanKuAg thanks for contributing
