### ISSUE TITLE
Website issue: The UI of the registration page i.e signup page needs to be fixed

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#139]
### Description

The left side of the page, that is the image needs to be fixed whereas the right side of the page needs to be scrollable, UI is bit broken so fix it

### Screenshots

![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/717d76f7-9f33-4b69-a5e9-f63e6ca70f44)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [ ] I am participating in IWOC
- [ ] I am willing to work on this issue (blank for no)

**Comment by Siddharth1605** [comment]
I'd like to work on this bug

**Comment by ItsRoy69** [comment]
Go for it

**Comment by Siddharth1605** [comment]
what I need to do on the image?

**Comment by ItsRoy69** [comment]
Follow the contributing guidelines from https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md and contribute to the registration page, gave the image as a screenshot where the fixation needs to be done

**Comment by Siddharth1605** [comment]
No, what Im asking is what to do the image in the signup page, should I reduce its size or make it a little adjacent to the form

**Comment by ItsRoy69** [comment]
Reduce the side if required but don't crop it up
