### ISSUE TITLE
Website issue: Features page needs responsivness

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#143]
### Description

While the features page is trying to access via mobile screens, we can see that the website is facing bugs and is not responsive

### Screenshots

![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/df904b92-4814-4099-8643-5fe1bb03bef5)
![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/883cf8ec-44f8-4abf-9b99-cc40d55a3040)

![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/f191cb10-ad91-42cf-95ed-17bcf1b58804)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [X] I am participating in IWOC
- [ ] I am willing to work on this issue (blank for no)

**Comment by mehedihasan2810** [comment]
hey @ItsRoy69 assign this to me

**Comment by ItsRoy69** [comment]
Go for it
