### ISSUE TITLE
Website issue: Rename the "lorem Ipsum" name of banner section and add a text 

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#145]
### Description

Rename the "lorem Ipsum" name of banner section to "John Doe" and under that add "Engineer" as text 

### Screenshots

![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/6994e57d-ee38-4d4a-8ca8-615928ef6f86)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [X] I am participating in IWOC
- [ ] I am willing to work on this issue (blank for no)

**Comment by ElenaExposito** [comment]
Hey @ItsRoy69! Can I take this issue?

**Comment by ItsRoy69** [comment]
Go for it
