### ISSUE TITLE
Bug: Add links to footer 

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#146]
### Description

Footer doesn't have proper links attached

### Proposed Solution

Add appropriate links to the footer section, 
- https://github.com/WikiPortal/DoodleCollab
- https://twitter.com/itsmeroy69
- https://www.linkedin.com/in/jyotirmoyroy69/
- Since we dont have behance account, thus we'll link to https://discord.com/invite/Ar84xkXkZt and place discord icon with same style in place of behnace
- Add https://doodlecollab.vercel.app/ link on the globe icon, though it is dribbble icon

### Screenshots

![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/858de1b7-5fa5-4145-b278-299802a07d34)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (leave this unchecked for no).

**Comment by kirtiraj22** [comment]
@ItsRoy69 can I work on it?

**Comment by ItsRoy69** [comment]
Go for it
