### ISSUE TITLE
📂Other: Implement Environment Variables for API URLs to Replace Hardcoded References

### ISSUE THREAD

**Issue by jayant-vashisth** [WikiPortal/DoodleCollab#156]
### What would you like to share?

The issue involves the presence of hardcoded API URL's (host) within the client side code, replace them with the help of environment variables.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [ ] I am participating in IWOC
- [X] I am willing to work on this issue (blank for no)

**Comment by ItsRoy69** [comment]
@jayant-vashisth I guess its unnecessary as we see the credentials are not exposed publically
