### ISSUE TITLE
fix the readme bug of adding the banner video from readme

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#16]
Eventhough I have added the line to add the banner video, but it is not showing on the readme.

![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/56591b1b-bf0a-400a-84c8-81e39ec16e99)

**Comment by isayanpal** [comment]
I want to work on this

**Comment by ItsRoy69** [comment]
go for it

**Comment by isayanpal** [comment]
Kindly Check the PR
Its fixed
