### ISSUE TITLE
Bug: After using eraser in sketch, cannot reuse brush. 

### ISSUE THREAD

**Issue by achyutagupta** [WikiPortal/DoodleCollab#160]
### Description

We can use eraser to erase the sketch made by brush, but cannot resuse the brush after using eraser.

### Proposed Solution

Adding a 'current state' type effect in erase button to tell we are currently using eraser or not. If we are not using eraser activate brush automatically.

### Screenshots

https://github.com/WikiPortal/DoodleCollab/assets/107514366/bf58dad0-2ceb-4ec8-9a05-ade14e8e3e59

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (leave this unchecked for no).

**Comment by ItsRoy69** [comment]
Go for it

**Comment by ItsRoy69** [comment]
Hey @achyutagupta can you just git pull ? as there was certain repitition of icons, thus removed few lines

**Comment by achyutagupta** [comment]
@ItsRoy69 Okay.
