### ISSUE TITLE
Website issue: Add a feature of screen recording the sketchbook, as you draw and share it.

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#161]
### Description

After users log in, they can record the screen that they are drawing and can share that recording with friends. Features will be just like other icons of menu.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [X] I am participating in JWOC
- [X] I am participating in IWOC
- [ ] I am willing to work on this issue (blank for no)

**Comment by ItsRoy69** [comment]
Go for it.

**Comment by Siddharth1605** [comment]
https://github.com/WikiPortal/DoodleCollab/assets/110531782/629a6c68-961d-465f-8de4-22093e90a913

I added the screen-recoding feature. Can you share the approach or idea for sharing this with friends, I think using email will be a possible solution for it

**Comment by Siddharth1605** [comment]
https://github.com/WikiPortal/DoodleCollab/assets/110531782/7390ad0a-9431-4988-b9b4-8237df802677

I added the screen recording feature. We can view the video, we can also download it. 
For sharing email will be an feasible solution.
![Sidd-screenrecording](https://github.com/WikiPortal/DoodleCollab/assets/110531782/523493e9-8330-47de-821f-39e462cbf998)
