### ISSUE TITLE
Website issue: Broken Layout

### ISSUE THREAD

**Issue by corners2wall** [WikiPortal/DoodleCollab#166]
### Description

Looks like broken layout

![Screenshot from 2024-02-01 13-48-46](https://github.com/WikiPortal/DoodleCollab/assets/110557519/e452bb04-3c2b-4034-9e39-b35fdab0687d)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [X] I am participating in JWOC
- [X] I am participating in IWOC
- [X] I am willing to work on this issue (blank for no)

**Comment by theRaven-code** [comment]
Can you assign me this? I'm interested to work on this issue!

**Comment by ItsRoy69** [comment]
#142 already mentioned the issue
