### ISSUE TITLE
Code refactoring ( & rewriting with Tailwind CSS )

### ISSUE THREAD

**Issue by theRaven-code** [WikiPortal/DoodleCollab#168]
### What would you like to share?

The code seems to be a bit scattered and going everywhere. I hope I could take on the task of refactoring to reduce the redundant codes, thereby increasing the developer experience. 

Also, the styling is really messy and static. I think I'd like to rewrite this in  Tailwind CSS (already opened issue). 

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [ ] I am participating in IWOC
- [X] I am willing to work on this issue (blank for no)

**Comment by ItsRoy69** [comment]
already mentioned the issue on #87 and @AryanKuAg is already working on it. It is time consuming. Thus will suggest  to join the discord and talk about working as a whole if you're okay with it.

**Comment by theRaven-code** [comment]
@ItsRoy69  cool. drop me the link

**Comment by ItsRoy69** [comment]
https://discord.com/invite/Ar84xkXkZt
