### ISSUE TITLE
There is a navbar in the sketchbook js, so kindly edit and modify the navbar with modern ui, which would look better

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#17]
Check sites like https://www.framer.com/, https://ui.aceternity.com/, https://www.classroomio.com/, https://www.classroomio.com/ to get ideas of navbar

Navbar should be modern UI

**Comment by KeyurGK** [comment]
I am willing to contribute to this issue. Looking forward to getting assigned.

**Comment by Pritam1136** [comment]
I would like to contribute in this issue

**Comment by KeyurGK** [comment]
> I would like to contribute in this issue

Hey I am contributing to it, once done you can build over it. Will be looking forward to the collaboration!

**Comment by Pritam1136** [comment]
OK!
