### ISSUE TITLE
Add About us page 

### ISSUE THREAD

**Issue by AbhineshJha** [WikiPortal/DoodleCollab#172]
### What would you like to share?

Wanna add a about us page in this website 

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [X] I am participating in IWOC
- [X] I am willing to work on this issue (blank for no)

**Comment by ItsRoy69** [comment]
The project's about is already declared
