### ISSUE TITLE
Use third party data fetching library like React query instead useEffect to get features like caching, revalidating and many more

### ISSUE THREAD

**Issue by mehedihasan2810** [WikiPortal/DoodleCollab#179]
### Description

Using useEffect to fetch data is not a good solution as it creates problem like race conditions also it is not ideal place for fetching data.

Use third party react data fetching library like [React Query](https://tanstack.com/query/latest/docs/framework/react/overview) to get features like caching, revalidating, optimistic update and many more.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [ ] I am participating in IWOC
- [X] I am willing to work on this issue (blank for no)

**Comment by ItsRoy69** [comment]
Go for it
