### ISSUE TITLE
Bug: Image logo on the sketchboard is not working

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#182]
### Description

When clicking on the image icon it functions nothing . 

### Proposed Solution

Users should be able to upload image as they click on the image icon 

### Screenshots

![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/2fb6335c-e74e-44ae-907e-46baae39574b)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (leave this unchecked for no).

**Comment by Abraham599** [comment]
should the image be displayed on the canvas after uploading at x:0 y:0 ?

**Comment by Abraham599** [comment]
@ItsRoy69 please assign this issue to me

**Comment by Abraham599** [comment]
@ItsRoy69 could you assign this issue to me ??
