### ISSUE TITLE
Website issue: Users should be able to download the drawn sketchboard 

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#184]
### Description

When clicking on the download icon, users are not able to download the drawn sketchbook in different formats like "jpg" , "png" and "jpeg" format. Add feature that when clicking on the download icon, users should be able to download the drawn sketchbook in different formats like "jpg" , "png" and "jpeg" format.

### Screenshots

![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/0343b7b2-9352-4956-963c-fd0cb1dee4d3)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [X] I am participating in IWOC
- [ ] I am willing to work on this issue (blank for no)

**Comment by Atharva-Nimbalkar** [comment]
Hello @ItsRoy69 Can you please assign this to me. I really want to contribute.
