### ISSUE TITLE
Bug: The sketchbook takes time to load from "Sorry login first" to "Sketchbook" componenent after loggin in

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#191]
### Description

When users log in for the first time, the page shows "Sorry login first" in the sketchbook at first and then shows the sketchbook loads. The signout button moves back to signup button as user refreshes after few seconds, it says that user details are not getting stored locally and thus creates issue as a developer

### Proposed Solution

When user logs in there should show the sketchbook immediately and 'sign out' button should stay as the datas gets stored on local storage until user clicks 'sign out' button. 

### Screenshots

[screen-capture (3).webm](https://github.com/WikiPortal/DoodleCollab/assets/78967360/e1700f88-010a-4250-b5b3-5e034c8bd1bd)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (leave this unchecked for no).

**Comment by mehedihasan2810** [comment]
@ItsRoy69 I would like to take a look at it
