### ISSUE TITLE
Bug: Sketchbook height needs to be fixed

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#199]
### Description

While user goes through the sketchbook code, it is seen to be a bit messy and complicated and difficult to read, thus needs to be cleaned up properly. As well as the skethbook componenet is not taking screen size as a whole, instead the size is exceeding the screen's height, so fix it

### Proposed Solution

The sketchbook should not be scrollable and the code should be readable and clean for users to properly understand.

### Screenshots

[screen-capture (4).webm](https://github.com/WikiPortal/DoodleCollab/assets/78967360/c442dcb0-2808-4044-b8a0-0569d6b8fbfe)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (leave this unchecked for no).

**Comment by rachana-uniyal** [comment]
Hi, I would like to work on this issue.
