### ISSUE TITLE
add an issue template with which we can decide the type of fixes

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#2]

**Comment by Bayyana-kiran** [comment]
can u please assign me i can work on this

**Comment by ItsRoy69** [comment]
Go for it

**Comment by Bayyana-kiran** [comment]
Can u give a brief description if u don't mind

**Comment by ItsRoy69** [comment]
I want templates for issues.. like folks can decide whether the issues are related to docs, bugs, website, and more. And certain templates will come... Go through repositories of various os orgs.. you'll see..
Can go through https://github.com/milanhub

**Comment by ItsRoy69** [comment]
@Bayyana-kiran since its been more than a month and its been inactive so assigning someone else
