### ISSUE TITLE
Website issue: Dark mode shouldn't be applied for the  sketchbook page

### ISSUE THREAD

**Issue by mehedihasan2810** [WikiPortal/DoodleCollab#210]
### Description

Do not apply dark mode in the sketchbook page. keep the page always in light mode

### Screenshots

![screencapture-doodlecollab-vercel-app-sketchbook-2024-02-10-13_22_11](https://github.com/WikiPortal/DoodleCollab/assets/117534561/09b2b606-98a5-4c9a-9080-0680a18f9c17)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [ ] I am participating in IWOC
- [ ] I am willing to work on this issue (blank for no)

**Comment by ItsRoy69** [comment]
Nah, its for user's help
