### ISSUE TITLE
Website issue: There is two dark-light mode toggle action. Which is redundant. Remove one

### ISSUE THREAD

**Issue by mehedihasan2810** [WikiPortal/DoodleCollab#211]
### Description

Right now there is two action button for toggling dark-light mode which is redundant. 

Remove the slider one.

### Screenshots

![Screen Shot 2024-02-10 at 13 29 38](https://github.com/WikiPortal/DoodleCollab/assets/117534561/5401d265-9f91-47f7-8d17-78cc4b57939e)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [ ] I am participating in IWOC
- [ ] I am willing to work on this issue (blank for no)

**Comment by ItsRoy69** [comment]
Its looking good though
