### ISSUE TITLE
Website issue: Remove material ui instead use a tailwind friendly component library

### ISSUE THREAD

**Issue by mehedihasan2810** [WikiPortal/DoodleCollab#212]
### Description

As we are using tailwind it would be better to use a tailwind friendly component library instead material UI.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [ ] I am participating in IWOC
- [X] I am willing to work on this issue (blank for no)

**Comment by Albert-2** [comment]
hey @ItsRoy69 
1. in userProfile or any other component material ui components are used; am i supposed to convert it into pure tailwind or use tailwindui library for tailwind components

**Comment by Albert-2** [comment]
cause you have used simple css , material ui components and pure tailwind also

**Comment by Albert-2** [comment]
okok

**Comment by Albert-2** [comment]
hey one question is there any open source event is currently up.....??

**Comment by ItsRoy69** [comment]
GSOC is going on

**Comment by Albert-2** [comment]
hey @ItsRoy69 
here is my PR
https://github.com/WikiPortal/DoodleCollab/pull/247/
Thank You...!!

**Comment by Albert-2** [comment]
hey @ItsRoy69
Made a new pr
here it is #249
