### ISSUE TITLE
Change design of buttons inside the editor

### ISSUE THREAD

**Issue by davidkrupa** [WikiPortal/DoodleCollab#26]
Some buttons do not require text inside to represent the functionality of the button. E.g.: bin icon instead of "clear", arrow icons instead of "undo", "redo". As the editor continues to grow, we will have more buttons. To make it easier to use and edit, we can install the react-icons library. So this issue contains 2 tasks:
- install react-icons library
- change button icons where it makes sense

**Comment by davidkrupa** [comment]
@ItsRoy69 please assign this task to me

**Comment by ItsRoy69** [comment]
Go for it

**Comment by ItsRoy69** [comment]
LGTM
