### ISSUE TITLE
Fixing the styling of the Save button

### ISSUE THREAD

**Issue by anand-harsh** [WikiPortal/DoodleCollab#32]
While saving, the "Save" button and the pop up is not styled properly. The save button is overflowing the popup

Screenshot:

![image](https://github.com/WikiPortal/DoodleCollab/assets/94885893/efedb32d-a47f-4c07-8fba-854efcf61b66)

Under Kwoc'23

**Comment by anand-harsh** [comment]
Please assign me this issue

**Comment by Pranay38** [comment]
Please assign me this

**Comment by ItsRoy69** [comment]
@anand-harsh are you still working on this issue ?

**Comment by anand-harsh** [comment]
> @anand-harsh are you still working on this issue ?

No
