### ISSUE TITLE
Fix: Color is not getting changed

### ISSUE THREAD

**Issue by AaadityaG** [WikiPortal/DoodleCollab#34]
Even after choosing the different color the color is not getting changed... as below

https://github.com/WikiPortal/DoodleCollab/assets/114663382/6838ed41-5560-4d10-ad72-39344329054e

Allow me to work on if for KWoC'23

**Comment by ItsRoy69** [comment]
@AaadityaG start working on the issues assigned

**Comment by AaadityaG** [comment]
Please add a tag of KWOC

**Comment by ItsRoy69** [comment]
Done
