### ISSUE TITLE
Add the dark mode button to nav bar 

### ISSUE THREAD

**Issue by AaadityaG** [WikiPortal/DoodleCollab#35]
Partcipating in KWoC

Please allow me to work on it!

**Comment by Pranay38** [comment]
Claim

**Comment by Pranay38** [comment]
Please assign this to me

**Comment by TusharGagal** [comment]
I can add Tailwind CSS and context API concept for a theme change and also I will style the button for that I had made a theme switcher application. I can fix this. Please assign this to me.
