### ISSUE TITLE
give a proper readme showing name, description, setup steps, cover image 

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#4]

**Comment by praptisharma28** [comment]
Assign me @ItsRoy69 , I can write a really good readme after reading the project in depth.

**Comment by ItsRoy69** [comment]
Sure, go with it

**Comment by praptisharma28** [comment]
Hey @ItsRoy69 , please add the difficulty level and iwoc24 and iwoc2024 tag. It will be show to my dashboard.

**Comment by ItsRoy69** [comment]
Did my part

**Comment by praptisharma28** [comment]
Here @ItsRoy69 https://github.com/WikiPortal/DoodleCollab/pull/48

**Comment by praptisharma28** [comment]
Added some badges too: for some reason was not able to commit in the same PR, may be cause I changes Readme directly. Hence check this too #49 @ItsRoy69

**Comment by ItsRoy69** [comment]
It'll be better if you add workflow.md and attach the file to readme where folks can see how the files are arranged, then a separate section for contributors.

**Comment by praptisharma28** [comment]
https://github.com/WikiPortal/DoodleCollab/pull/51 @ItsRoy69

**Comment by praptisharma28** [comment]
Please close this issue @ItsRoy69 . The points are not showing on my dashboard. If you want any other enhancement , open a new issue please.
