### ISSUE TITLE
Add: illustrative home page

### ISSUE THREAD

**Issue by AaadityaG** [WikiPortal/DoodleCollab#40]
Please allow me to work on it with KWOC tag!

**Comment by praptisharma28** [comment]
Assign me this @ItsRoy69 under iwoc24. I can work if @AaadityaG is not working on it.

**Comment by ItsRoy69** [comment]
@AaadityaG since its been more than a week and its been inactive so assigning to @praptisharma28

**Comment by ItsRoy69** [comment]
@praptisharma28 can go for it

**Comment by ItsRoy69** [comment]
@praptisharma28 are you still working on this issue ?

**Comment by praptisharma28** [comment]
@ItsRoy69 yes I am wait for my PR

**Comment by ItsRoy69** [comment]
Okay

**Comment by praptisharma28** [comment]
@ItsRoy69 please add the tags.

**Comment by praptisharma28** [comment]
![Screenshot (547)](https://github.com/WikiPortal/DoodleCollab/assets/123169861/3e03300a-28fc-4216-b659-eee929deae07)

**Comment by ItsRoy69** [comment]
This looks good

**Comment by praptisharma28** [comment]
#123 have a look @ItsRoy69
