### ISSUE TITLE
Home ????

### ISSUE THREAD

**Issue by nepalivai** [WikiPortal/DoodleCollab#53]
So many questions including, Why?
<img width="960" alt="image" src="https://github.com/WikiPortal/DoodleCollab/assets/108126089/3ce288fb-6fb8-4f2a-8b7a-edba0f3b79d9">

**Comment by ItsRoy69** [comment]
There were certain issues that needed to be fixed, so fixed it. check now. It was declared to give a homepage to the doodlecollab, more fixes are pending will do soon

**Comment by Siddharth1605** [comment]
@ItsRoy69 the home page still looks the same in vercel, if there are things to do in homepage, I would like to do that, you can assign me

**Comment by nepalivai** [comment]
NHA! stills looks same to me.
