### ISSUE TITLE
Blog page

### ISSUE THREAD

**Issue by Siddharth1605** [WikiPortal/DoodleCollab#59]
I'd like to develop the blog page, if there are any designs share it, and can you assign me for this

**Comment by ItsRoy69** [comment]
Hey, thanks for taking the decision to apply, I am thinking of desitning the blogging app like below :

![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/4d871055-62c1-4f31-9a2c-cd7f5d643974)

**Comment by Siddharth1605** [comment]
Ok @ItsRoy69 , I'll develop the react page and raise PR as soon as possible. Could you give more info on the contents of the page or just random texts?

**Comment by ItsRoy69** [comment]
Keep lorem ipsum for now, thinking of making an admin section in future
