### ISSUE TITLE
Give a banner to the homepage , maintaining industry standards in writing the code.

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#64]
I have added a design which users can follow to do the banner image of the homepage. 

1. Before coding the banner, remember to make a folder named 'components' inside 'src' folder
2. Inside that components folder add a folder named 'Banner, now inside that folder add 'HomeBanner.jsx' and 'homebanner.css'
3. Inside the 'HomeBanner.jsx' follow the below design pattern and code it
4. Call that 'HomeBanner.jsx' inside 'Home.jsx' file
5. Give a proper commit and declare issue number before pull request
 
![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/f34e2426-edeb-43a1-ad02-32a24c960ba4)

**Comment by YashNuhash** [comment]
> I have added a design which users can follow to do the banner image of the homepage.
> 
> 1. Before coding the banner, remember to make a folder named 'components' inside 'src' folder
> 2. Inside that components folder add a folder named 'Banner, now inside that folder add 'HomeBanner.jsx' and 'homebanner.css'
> 3. Inside the 'HomeBanner.jsx' follow the below design pattern and code it
> 4. Call that 'HomeBanner.jsx' inside 'Home.jsx' file
> 5. Give a proper commit and declare issue number before pull request
> 
> ![image](https://private-user-images.githubusercontent.com/78967360/297769261-f34e2426-edeb-43a1-ad02-32a24c960ba4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4OTg5MDgsIm5iZiI6MTcwNTg5ODYwOCwicGF0aCI6Ii83ODk2NzM2MC8yOTc3NjkyNjEtZjM0ZTI0MjYtZWRlYi00M2ExLWFkMDItMzJhMjRjOTYwYmE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA0NDMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlMDM0NmRkYTk2ZThjOTg5Zjk1NDQxZmU2MWY5ZjI0NmZlMjc2MTUwNzc2OTkxYjliNmMyNzI5MGI0MzgwMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p4z-Xoafuh9aDsi9DHbgQzcNKPB8xoHqRgn1nGklSpM)

**Ok, fine. in the middle profile card of "john doe" inside of it there is an image of another profile card , where can I get this ?**

**Comment by ItsRoy69** [comment]
For now you can add a dummy image

**Comment by ItsRoy69** [comment]
@YashNuhash are you working on this issue ?

**Comment by YashNuhash** [comment]
> @YashNuhash are you working on this issue ?

Yes

**Comment by praptisharma28** [comment]
Assign me @ItsRoy69

**Comment by YashNuhash** [comment]
> Assign me @ItsRoy69

![image](https://github.com/WikiPortal/DoodleCollab/assets/106915718/fdc180be-2153-4b7b-b707-6f7cfae929df)

I would like to encourage you to consider contributing to other issues as I am already working for this .

**Comment by ItsRoy69** [comment]
@praptisharma28 since @YashNuhash was having conversation and assured that he's gonna work there, so he
