### ISSUE TITLE
Give a about section to the homepage , maintaining industry standards in writing the code.

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#66]
I have added a design which users can follow to do the about image of the homepage. 

1. Before coding the about section just below the banner section, remember to make a folder named 'components' inside 'src' folder
2. Inside that components folder add a folder named 'About' , now inside that folder add 'HomeAbout.jsx' and 'homeabout.css'
3. Inside the 'HomeAbout.jsx' follow the below design pattern and code it
4. Call that 'HomeAbout.jsx' inside 'Home.jsx' file
5. Icons are not given to the given screenshot, just for refernece use icons 'https://www.flaticon.com/free-icon/creative-writing_10064323?term=idea&page=1&position=32&origin=search&related_id=10064323&k=1705595712253&sign-up=google'
6. Give a proper commit and declare issue number before pull request
 

![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/2e40133b-c45e-46db-bf19-3bbd948733a6)

**Comment by Srinkk** [comment]
I want to work on this issue. Please assign me.
