### ISSUE TITLE
Give a navigation section to the footer of the homepage , maintaining industry standards in writing the code.

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#69]
I have added a design which users can follow to do the navigation section just above the footer of the homepage. 

1. Before coding the navigation section just above the footer section, remember to make a folder named 'components' inside 'src' folder
2. Inside that components folder add a folder named named 'NavFooter' inside 'components' folder, now inside that folder add 'FooterMenu.jsx' and 'footermenu.css'
3. Inside the 'FooterMenu.jsx' follow the below design pattern and code it
4. Call that 'FooterMenu.jsx' inside 'Home.jsx' file
5. Give a proper commit and declare issue number before pull request
 

![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/44e98c61-2dce-485b-a4ea-3965578fbee0)

**Comment by n0n3br** [comment]
@ItsRoy69 please provide de links each icon should point to

**Comment by YashNuhash** [comment]
let me assign for this issue

**Comment by YashNuhash** [comment]
> I have added a design which users can follow to do the navigation section just above the footer of the homepage.
> 
> 1. Before coding the navigation section just above the footer section, remember to make a folder named 'components' inside 'src' folder
> 2. Inside that components folder add a folder named named 'NavFooter' inside 'components' folder, now inside that folder add 'FooterMenu.jsx' and 'footermenu.css'
> 3. Inside the 'FooterMenu.jsx' follow the below design pattern and code it
> 4. Call that 'FooterMenu.jsx' inside 'Home.jsx' file
> 5. Give a proper commit and declare issue number before pull request
> 
> ![image](https://private-user-images.githubusercontent.com/78967360/297966292-44e98c61-2dce-485b-a4ea-3965578fbee0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NTc1NjUsIm5iZiI6MTcwNTc1NzI2NSwicGF0aCI6Ii83ODk2NzM2MC8yOTc5NjYyOTItNDRlOThjNjEtMmRjZS00ODViLWE0ZWEtMzk2NTU3OGZiZWUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDEzMjc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMmI5NmI0YzBlNTEzM2E0N2IxN2Y0NDMzOTJhYTk4ZjYzZjcwNjhhMWM2Nzg5ZTk1MTc2NDhjNWU0ZDljMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KJZERvT2rJLrNdBz2e52LbKooaQFK_DNkR1dlegxJZQ)

### what are those two icons after github icon and before the twitter icon ?

**Comment by ItsRoy69** [comment]
@n0n3br not necessary for the href links to be connected to for now

**Comment by ItsRoy69** [comment]
@YashNuhash its dribble and behance

**Comment by ItsRoy69** [comment]
@YashNuhash if you're thinking of working on this section, then I'll assign you. Don't start working directly

**Comment by YashNuhash** [comment]
> @YashNuhash if you're thinking of working on this section, then I'll assign you. Don't start working directly

**Yes, I am thinking to work on this section**

**Comment by Jenis07** [comment]
Can you please assign me this issue under IWOC?

**Comment by ItsRoy69** [comment]
@Jenis07 can you work on other issue assigwnd under iwoc ?

**Comment by Jenis07** [comment]
No
