### ISSUE TITLE
Give a faq section to the footer of the homepage , maintaining industry standards in writing the code.

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#70]
I have added a design which users can follow to do the navigation section just above the footer of the homepage. 

1. Before coding the faq section just above the footer section, remember to make a folder named 'components' inside 'src' folder
2. Inside that components folder add a folder named named 'Faq' inside 'components' folder, now inside that folder add 'Faq.jsx' and 'faq.css'
3. Inside the 'Faq.jsx' follow the below design pattern and code it
4. Call that 'Faq.jsx' inside 'Home.jsx' file
5. Give a proper commit and declare issue number before pull request

 ![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/83fe53bf-9e4b-4175-951d-7576b980242e)

**Comment by Srinkk** [comment]
I want to work on this issue. Please assign me.

**Comment by ItsRoy69** [comment]
Go for it

**Comment by YashNuhash** [comment]
> I have added a design which users can follow to do the navigation section just above the footer of the homepage.
> 
> 1. Before coding the faq section just above the footer section, remember to make a folder named 'components' inside 'src' folder
> 2. Inside that components folder add a folder named named 'Faq' inside 'components' folder, now inside that folder add 'Faq.jsx' and 'faq.css'
> 3. Inside the 'Faq.jsx' follow the below design pattern and code it
> 4. Call that 'Faq.jsx' inside 'Home.jsx' file
> 5. Give a proper commit and declare issue number before pull request
> 
> ![image](https://private-user-images.githubusercontent.com/78967360/297969491-83fe53bf-9e4b-4175-951d-7576b980242e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MjQyNjksIm5iZiI6MTcwNTcyMzk2OSwicGF0aCI6Ii83ODk2NzM2MC8yOTc5Njk0OTEtODNmZTUzYmYtOWU0Yi00MTc1LTk1MWQtNzU3NmI5ODAyNDJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDA0MTI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNWRhZDBlMGNmYjUyYTE5NDMzMzhlYmViY2E2NjliNjM5ZGQxOThkYmMxZmEzMGJlMjg3NWUxMTE0ZTZiMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7GyHgN5gxk-4C_3068al-QzBjYexBNPWua4L6EG9C0s)

### let me work on this issue, I also want to collaborate

**Comment by ItsRoy69** [comment]
@YashNuhash thanks but I've already assigned @Srinkk ,so it'll be great if you work on other issue
