### ISSUE TITLE
Modify the registration page maintaining industry standards in writing the code

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#71]
I have added a design which users can follow to do the registration page of the webpage. 

Follow the industry standards and modify the code of the 'Register.jsx' page which is inside the Authentication folder accordingly (https://github.com/WikiPortal/DoodleCollab/blob/main/src/pages/Authentication/Register.jsx) .

Give a proper commit and declare issue number before pull request

[Doodlecollab.webm](https://github.com/WikiPortal/DoodleCollab/assets/78967360/2f465d23-5898-4bcb-9de8-ebeb61a75ced)

**Comment by 1-ankush-1** [comment]
- Hey i want to work on this issue please assign this issue to me .

## suggestion
 - instead of defining severals states for email,password,name. we can create a single state and handel input accordingly.

**Comment by 1-ankush-1** [comment]
@ItsRoy69 do you have this above image?

**Comment by ItsRoy69** [comment]
@1-ankush-1 Yes, if you're taking about the image on the left side of the registration then its https://i.pinimg.com/originals/d5/a5/2b/d5a52b1a1e36efaa37f247e6c5f8c7f8.jpg
and for the image as a whole 
![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/f01470e8-1195-4d6d-8073-78f2b74799f7)

**Comment by Srinkk** [comment]
Hello, I want to contribute to this project. Please assign me this task.

**Comment by ItsRoy69** [comment]
I guess @1-ankush-1 is already working on this issue, you can look into other issues.

**Comment by 1-ankush-1** [comment]
sorry for the late reply . I'm preoccupied you can assign this issue to someone else @ItsRoy69 .

**Comment by ItsRoy69** [comment]
ok sure
