### ISSUE TITLE
Give a joinus section to then homepage , maintaining industry standards in writing the code.

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#72]
I have added a design which users can follow to do the joinus section on the homepage. 

1. Before coding the joinus section, remember to make a folder named 'components' inside 'src' folder
2. Inside that components folder add a folder named named ' JoinUs' inside 'components' folder, now inside that folder add 'JoinUs.jsx' and 'joinus.css'
3. Inside the 'JoinUs.jsx' follow the below design pattern and code it
4. Call that 'JoinUs.jsx' inside 'Home.jsx' file
5. Give a proper commit and declare issue number before pull request
6. The background color for reference is : linear-gradient(163deg,#022d2b,#000000)

 ![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/7e31d8ca-1ac0-48b1-bff1-550f7d56e4b5)

**Comment by hiCXK** [comment]
Hi @ItsRoy69 :wave:  please assign me this issue. Working on this.

**Comment by hiCXK** [comment]
Made this now: 
![image](https://github.com/WikiPortal/DoodleCollab/assets/123109957/f2ac59bc-4eaa-41e8-b231-4b750ad55355)

**Comment by ItsRoy69** [comment]
@hiCXK make a PR please
