### ISSUE TITLE
Feature Page

### ISSUE THREAD

**Issue by Siddharth1605** [WikiPortal/DoodleCollab#86]
I'd like to develop the feature page.

**Comment by ItsRoy69** [comment]
You can go for it, attaching the design 

1. Before coding the feature page, remember to make a folder named ''Feature"  inside 'pages' folder
2. Inside that pages folder add a 'Feature.jsx' and ''feature.css'
3. Inside the ''Feature.jsx' follow the below design pattern and code it
4. Call that ''Feature.jsx' inside 'App.jsx' file
5. Give a proper commit and declare issue number before pull request
6. For reference images :
![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/bfd2d426-c8e9-41af-b8a8-9b59fc3cb864)
![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/e8351a97-7f32-47db-8403-c0e99c51b49b)

7. The links that will be connected to Kharagpur Winter of Code is https://kwoc.kossiitkgp.org/, Netaji Subhash Engineering College Winter of Code is https://winterofcode.com/ and Innogeeks Winter of Code is https://iwoc.codes/
----
The feature page design:


![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/2ba18708-b4d9-4a89-bb31-33e0514f3f08)
