### ISSUE TITLE
Make a signing out functionality

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#88]
Make a condition that if someone is already logged in then signup button should change to signout text and the signing out functionality should happen in the navbar.

The functionaility is already given just needs to make some changes in the navbar section, such that the signup button changes to signout button and user can signout, below is the functionality that needs to be fixed.

![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/6f90c562-6169-4db0-beef-a58b4d703d84)

**Comment by ItsRoy69** [comment]
Sure, go for it

**Comment by ItsRoy69** [comment]
@Jenis07 unassigning as the task is not completed by the contributing guidelines date

**Comment by BrijPatel15** [comment]
Can I give this a shot?

**Comment by ItsRoy69** [comment]
Go for ir

**Comment by Prasundas99** [comment]
Still open?

**Comment by vinayak3010** [comment]
sir please assign me this issue, if it is not closed yet
