### ISSUE TITLE
Add a routing section "sorry login first" if not logged in

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#89]
Add a routing section functionality that if user tries to access the sketchbook page without logging in then the page should show "sorry login first"

**Comment by Tharuneshwarv** [comment]
@ItsRoy69 can i work on this issue?

**Comment by Tharuneshwarv** [comment]
@ItsRoy69 i'm getting cors issue. I would like to know how you are dealing with this issue. Also, i would like to add additional api to validate token.

**Comment by ItsRoy69** [comment]
@Tharuneshwarv can you share a screenshot of the issue you're facing ?

**Comment by Tharuneshwarv** [comment]
No  issues. I have fixed. Working on the issue. Also, Can i add api for token validation ?

**Comment by ItsRoy69** [comment]
Sure

**Comment by Tharuneshwarv** [comment]
@ItsRoy69  i have added PR: https://github.com/WikiPortal/DoodleCollab/pull/103 . If any changes need to be made. Let me know.

**Comment by Tharuneshwarv** [comment]
@ItsRoy69 i would like to know about quality of code, that i delivered.

**Comment by ItsRoy69** [comment]
Though the quality of code looks good and it follows the coding standards like readability, and mostly followed the initial coding standards of the rest of codebase but naming of files and folder names needed a change as 'CamelCase',  and spacing was given. In the server folder adding a rate-limitor in the routing would've made a better production ready coding practice like using of 'express-rate-limit' package
