### ISSUE TITLE
Modify the design of the blog page from "Blog.jsx" 

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#91]
Modify the styling of the blogs page according to the below given desing, if required make a blogs.css file to include the styling of the blog page

![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/53052e7f-d9cf-4501-a2fc-28c3c17e41bc)

**Comment by hemanth-kumar-boddeda** [comment]
Hi @ItsRoy69 , kindly assign this to me

**Comment by hemanth-kumar-boddeda** [comment]
kindly check the below snip, and let me know if you need any more changes
https://github.com/WikiPortal/DoodleCollab/assets/82110100/c4576d21-06f7-4195-8ff2-ab54edda47ef

**Comment by ItsRoy69** [comment]
It is not designed according to the given picture

**Comment by ItsRoy69** [comment]
@hemanth-kumar-boddeda are you still working on this

**Comment by hemanth-kumar-boddeda** [comment]
Yes @ItsRoy69 I will provide it by tomorrow

**Comment by AryanKuAg** [comment]
Hi @ItsRoy69 , I've fixed this issue and also raised PR for this here -> https://github.com/WikiPortal/DoodleCollab/pull/155
Pls merge the code🙂 and could u pls make me a contributor of this project and add my profile in the project's readme.md file, nobody has ever added me, pls, it will make my day🙏

**Comment by ItsRoy69** [comment]
@AryanKuAg idk why you made a PR when you can see @hemanth-kumar-boddeda is already assigned. Will merge your PR if @hemanth-kumar-boddeda doesn't provide the PR

**Comment by AryanKuAg** [comment]
Apology, I was thinking open sourcing as a competition that I could provide a better UI before anyone and my code will get selected. Now I get the flow like first I should ask the author to assign the task then you can work. Its the group collab. Thanks @ItsRoy69 for clarifying it. I'm now looking for open tasks in this repo and as I find something, I'll follow the procedure. Thanks again🙂.

**Comment by ItsRoy69** [comment]
You can also create issues as you can see I feel many features can be added like reacording the whiteboards,live sharing and more, opensource is about patience.

**Comment by AryanKuAg** [comment]
Sure. I'll do that.

**Comment by jaymehta002** [comment]
@ItsRoy69  assign me this issue

**Comment by jaymehta002** [comment]
Give this a look and suggest changes 
## screenshot
![Screenshot 2024-01-30 135816](https://github.com/WikiPortal/DoodleCollab/assets/40739838/3710559f-cdd9-4744-a834-0d1065dd2641)
![Screenshot 2024-01-30 135802](https://github.com/WikiPortal/DoodleCollab/assets/40739838/e820d8a2-0606-464f-b76d-1caa0fbdf3a3)

**Comment by ItsRoy69** [comment]
@hemanth-kumar-boddeda unassigning as the task is not competed by the contributing guidelines date
