### ISSUE TITLE
Website issue: When logged in, there should appear a profile section on the right side of the sketchbook

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#92]
### Description

When user logs in, the user should be able to see the profile section showing his/her username and a dummy image if no image is uploaded while signing up, on the right top side of the sketchbook page

In the attached screenshot I have shown where "lorem ipsum" and a circle logo is given, do accordingly

### Screenshots

![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/7a76bff0-589c-4a66-b4de-642ffa1fbe72)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [ ] I am participating in IWOC
- [ ] I am willing to work on this issue (blank for no)

**Comment by Bikram-ghuku** [comment]
Can I work on this issue? Please assign this to me

**Comment by ItsRoy69** [comment]
> Can I work on this issue? Please assign this to me

go for it

**Comment by ItsRoy69** [comment]
> Hey @ItsRoy69 you can assign this to me if it is not assigned yet

since I've already assigned @Bikram-ghuku for the profile section, can you create another issue and work on the menu section styling which I've show in the given image

**Comment by Bikram-ghuku** [comment]
Wont be able to work on it until issue #112 is fixed, as I wount be able to login in.

**Comment by ItsRoy69** [comment]
@Bikram-ghuku thr sketchbook page is inside the folder structure, you can use commenting in your localhost for working on the sketchbook page
