### ISSUE TITLE
Website issue: When logged in, there should appear a menu section on the middle side of the sketchbook

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#93]
### Description

When user logs in, the user should be able to see the menu section showing up as a drawer which includes all the functionality on the horizontally centre top side of the sketchbook page instead of previously menu showing accordingly

In the attached screenshot I have shown where "menus" are given, do accordingly.

The menu should pop up show like a drawer, use framer motion or any modules if needed

### Screenshots

![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/7a76bff0-589c-4a66-b4de-642ffa1fbe72)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [ ] I am participating in IWOC
- [ ] I am willing to work on this issue (blank for no)

**Comment by ItsRoy69** [comment]
okay

**Comment by hemanth-kumar-boddeda** [comment]
@ItsRoy69 I have added the drawer to the sketchbook page, but login is a blocker for me, could you please respond for this?

**Comment by hemanth-kumar-boddeda** [comment]
https://github.com/WikiPortal/DoodleCollab/assets/82110100/58f46a6a-178d-41db-8b0d-0b82b82277c5

check the above snip where i have solved many issues, hope to hear from you soon.

**Comment by ItsRoy69** [comment]
@hemanth-kumar-boddeda eventough your work looks good but its not solving the mentioned issue, kindly work on the issues according to the instructions which are being assigned

**Comment by hemanth-kumar-boddeda** [comment]
@ItsRoy69 , I have worked on skecthbook as well and it is completed but server is not responding to the credentials given, kindly check that

**Comment by ItsRoy69** [comment]
@hemanth-kumar-boddeda did you check the mentioned steps for setting up the server side codebase ?

**Comment by ItsRoy69** [comment]
@hemanth-kumar-boddeda and for working on the banner section kindly check #64 for the design, ask for assigning and then after getting assigned start working on it, for working on the registration page kindly check #71 for the design, ask for assigning and then after getting assigned start working on it.

**Comment by hemanth-kumar-boddeda** [comment]
Hi @ItsRoy69 , could you please mention the names of the first icon which is present in menu drawer.

**Comment by ItsRoy69** [comment]
@hemanth-kumar-boddeda go to https://thenounproject.com/ and find icons by searching select, eraser, pencil, landscape, dustbin, download, share, shapes, pdf

**Comment by hemanth-kumar-boddeda** [comment]
@ItsRoy69 Thanks Brother

**Comment by ItsRoy69** [comment]
@hemanth-kumar-boddeda unassigning as the task is not completed by the contributing guidelines date

**Comment by mehedihasan2810** [comment]
hey @ItsRoy69 I would like to work on this issue. Please assign this to me
