### ISSUE TITLE
Website issue: Added a "TrustDevelopers" section just below the HomeBanner section

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#94]
### Description

I have added a design which users can follow to do the TrustDevelopers of the homepage. 

1. Before coding the TrustDevelopers section, remember to make a folder named 'TrustDevelopers' inside the components folder, now inside that folder add 'TrustDevelopers.jsx' and 'trustdevelopers.css'
3. Inside the 'TrustDevelopers.jsx' follow the below design pattern and code it
4. Call that 'TrustDevelopers.jsx' inside 'Home.jsx' file
5. Give a proper commit and declare issue number before pull request
6. Links to all logos are : https://fellowship.keploy.io/images/logo.png , https://www.gstatic.com/devrel-devsite/prod/v838cdd0153469aefad6dfec4f5808816c5382d891c64c2a3c5aaefbf46a914dd/firebase/images/lockup.svg, https://mirror-ai.com/ , https://1000logos.net/wp-content/uploads/2020/08/MongoDB-Logo.jpg

### Screenshots

![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/aa4f1bde-b6ca-468a-9dfd-23b4f00fd971)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [ ] I am participating in IWOC
- [ ] I am willing to work on this issue (blank for no)

**Comment by ItsRoy69** [comment]
Go for it

**Comment by praptisharma28** [comment]
@ItsRoy69 , you have used both easy and medium tag, please use one otherwise it may create issue on dashboard.

**Comment by praptisharma28** [comment]
![image](https://github.com/WikiPortal/DoodleCollab/assets/123169861/9797db10-c1b8-4317-9a49-ca423564d9c0)
Have a look @ItsRoy69

**Comment by ItsRoy69** [comment]
my bad.. @praptisharma28 , the given screenshot looks good. I want you to add this section just below the banner section, and above the "About" section

**Comment by praptisharma28** [comment]
No problem @ItsRoy69 have a look now!
![image](https://github.com/WikiPortal/DoodleCollab/assets/123169861/44f57c0c-0b58-4c65-8d53-1e9bf8bc6906)

**Comment by ItsRoy69** [comment]
LGTM, and suggestion: kindly remember to crop the images/screenshots accordingly in proper way before mentioning publicly for your privacy reasons
