### ISSUE TITLE
[Feature]: Add the github action workflow for greeting contributors

### ISSUE THREAD

**Issue by praptisharma28** [WikiPortal/DoodleCollab#95]
### What would you like to share?

Description
The current project lacks an automated action to greet contributors. GitHub Actions can significantly enhance project automation. I propose adding a GitHub Action workflow to greet new pull request (PR) and issue creators, fostering a welcoming environment.

Proposed Changes:
Implement a GitHub Action workflow that triggers on new PRs and issues. The workflow should include a greeting message to acknowledge and appreciate the contributors for their efforts.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [X] I am participating in IWOC
- [X] I am willing to work on this issue (blank for no)

**Comment by praptisharma28** [comment]
Please assign me this @ItsRoy69 under iwoc24

**Comment by ItsRoy69** [comment]
Go for it
