### ISSUE TITLE
Bug: When the website is put to dark mode, the boxes of the "About" remains white colored

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#98]
### Description

When I make the website dark mode, the boxes of the features i.e "Bring Ideas to Live" , "Component Templates" , "Project Management" and " Live Collaboration"remains white which needs a small fixation. 

When the website is made to dark mode the boxes should have a backgound image as 
![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/44679a8e-a17c-413a-8975-fb03ee24c737)

### Proposed Solution

It should look like below image when put to dark mode

### Screenshots

![image](https://github.com/WikiPortal/DoodleCollab/assets/78967360/fb49bdc8-43b6-438b-97f9-5529daf42f38)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (leave this unchecked for no).

**Comment by YashNuhash** [comment]
This issue is fit for me, You can assign me for this

**Comment by ItsRoy69** [comment]
Sure, go for it
