### ISSUE TITLE
Website issue: Make the navbar fixed to top

### ISSUE THREAD

**Issue by ItsRoy69** [WikiPortal/DoodleCollab#99]
### Description

I dont want the navbar to go up ad i scroll up the website so make it fixed

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/WikiPortal/DoodleCollab/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/WikiPortal/DoodleCollab/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [ ] I am participating in IWOC
- [ ] I am willing to work on this issue (blank for no)

**Comment by godspeed-03** [comment]
Hii @ItsRoy69 , I would like to work on this issue. Please assign it to me.

**Comment by ItsRoy69** [comment]
Go for it

**Comment by hemanth-kumar-boddeda** [comment]
@ItsRoy69 I have fixed the navbar to top where if you scroll down the user can view the navbar as its position fixed
https://github.com/WikiPortal/DoodleCollab/assets/82110100/782e0d56-d485-49ac-a8d4-6b0ced067a28
